#include <algorithm>
#include <RooStats/ProfileLikelihoodCalculator.h>
#include <RooStats/LikelihoodIntervalPlot.h>
#include <TSystem.h>
#include <TLatex.h>
#include "StandardHypoTestInvDemo.C"

void Limit_RaaNS_Workspace(
    float ptLow=4, float ptHigh=6,
    float yLow=0, float yHigh=1.2,
    int cLow=0, int cHigh=200,
    float muPtCut=4.0
    ){

  const string poiname="raa3";
  const char *pdfname="joint";
  const char *wsname="wcombo";
  double CI = 0.95;

  const string filename=Form("/afs/cern.ch/work/g/goni/Analysis/Upsilon/upslion_Raa/Usercode/upperlimit/results/%s/fitResults_combo_pt%.1f_%.1f_y%.1f_%.1f_cent%d_%d_muPt%.1f.root",poiname.c_str(),ptLow,ptHigh,yLow,yHigh,cLow,cHigh,muPtCut);

  gSystem->mkdir(Form("/afs/cern.ch/work/g/goni/Analysis/Upsilon/upslion_Raa/Usercode/upperlimit/results/%s",poiname.c_str()),1);

  RooRealVar *theVar; RooDataSet *data; RooAbsPdf *pdf;
  // Open input file with workspace (generated by rf14_wspacewrite)
  TFile *f = new TFile(filename.c_str()) ;
  // Open text file to write results
  ofstream of(Form("results/%s/results_pt%.1f_%.1f_y%.1f_%.1f_cent%d_%d.txt",poiname.c_str(),ptLow,ptHigh,yLow,yHigh,cLow,cHigh));
  // Retrieve workspace from file
  RooWorkspace* ws = (RooWorkspace*) f->Get(wsname);
  RooStats::ModelConfig *sbHypo = (RooStats::ModelConfig*) ws->obj("SbHypo");
  RooStats::ModelConfig *bHypo = (RooStats::ModelConfig*) ws->obj("BHypo");
  cout << "observables: " << sbHypo->GetObservables()->getSize() << endl;
  theVar = ws->var(poiname.c_str());
  // if (!theVar) theVar = ws->function(poiname);
  pdf = ws->pdf(pdfname);
  data =(RooDataSet *) ws->data("data");
  // Print structure of composite p.d.f.
  pdf->Print("t") ;
  of << "Scanning " << filename.c_str() << " using the POI " << poiname.c_str() << ", the pdf " << pdfname << " and the workspace " << wsname << " with CL " << CI << endl;
  ws->loadSnapshot("SbHypo_poiAndNuisance_snapshot");
  of << poiname.c_str() << " " << theVar->getVal() << endl;
  // get a first estimate of where to look
  ProfileLikelihoodCalculator pl(*data,*sbHypo,1.-CI);
  cout << data << " " << pdf << " " << theVar << endl;
  pl.SetConfidenceLevel(CI); 
  //double ci = 100*CI;
  int ci = 100*CI;
  LikelihoodInterval* interval = pl.GetInterval();
  LikelihoodIntervalPlot plot(interval);
  TCanvas c4; c4.cd(); 
  plot.SetRange(0.,1,0.05,3.);
  plot.Draw();
  TLatex latexCI;
  latexCI.SetNDC();
  latexCI.SetTextSize(0.035);
  //latexCI.DrawLatex(0.5,1.-0.05*2,Form("%s %d % C.I.",poiname.c_str(),ci));
  latexCI.DrawLatex(0.5,1.-0.05*2,Form("%s %i \% C.I.",poiname.c_str(),ci));
  latexCI.DrawLatex(0.5,1.-0.05*3,Form("Upper limit: %f",interval->UpperLimit(*theVar)));
  latexCI.DrawLatex(0.5,1.-0.05*4,Form("Lower limit: %f",interval->LowerLimit(*theVar)));
  TString intrvlName = theVar->GetTitle();
  // print out the iterval on the Parameter of Interest
  cout <<endl<< CI <<"\% interval on " <<theVar->GetName()<<" is : ["<<
    interval->LowerLimit(*theVar) << ", "<<
    interval->UpperLimit(*theVar) << "] "<<endl;
  pair<double, double> CnfdncIntrvl;
  CnfdncIntrvl.first  = interval->LowerLimit(*theVar);
  CnfdncIntrvl.second = interval->UpperLimit(*theVar);
  c4.SaveAs(Form("results/%s/ULtest_pt%.1f_%.1f_y%.1f_%.1f_cent%d_%d.pdf",poiname.c_str(),ptLow,ptHigh,yLow,yHigh,cLow,cHigh));
  // pair<double, double> CnfdncIntrvl;
  // CnfdncIntrvl.first  = theVar->getVal()+theVar->getErrorLo();
  // CnfdncIntrvl.second = theVar->getVal()+theVar->getErrorHi();

  of << 100.*CI << "\% CL confidence interval from a likelihood scan on " << poiname.c_str() << endl;
  of << CnfdncIntrvl.first << " " << CnfdncIntrvl.second << endl;

  // now let's move to the hypo test inverter
  /////////////////////////////////////////////////////////////
  // Now get the POI for convenience
  // you may want to adjust the range of your POI
  ////////////////////////////////////////////////////////////
  RooRealVar* firstPOI = (RooRealVar*) sbHypo->GetParametersOfInterest()->first();
  double poimin = 0.5*max((double) 0.,CnfdncIntrvl.first);
  double poimax = 1.5*CnfdncIntrvl.second;
  cout << "Will scan between " << poimin << " and " << poimax << endl;
  // firstPOI->setMin(poimin);
  // firstPOI->setMax(poimax);
  cout << "POI defined between" << firstPOI->getMin() << " and " << firstPOI->getMax() << endl;

  // actually run the hypo test inverter

  // define calc type and test stat type
  // type = 0 Freq calculator 
  // type = 1 Hybrid calculator
  // type = 2 Asymptotic calculator  
  // type = 3 Asymptotic calculator using nominal Asimov data sets (not using fitted parameter values but nominal ones)
  //
  // testStatType = 0 LEP
  //              = 1 Tevatron 
  //              = 2 Profile Likelihood two sided
  //              = 3 Profile Likelihood one sided (i.e. = 0 if mu < mu_hat)
  //              = 4 Profile Likelihood signed ( pll = -pll if mu < mu_hat) 
  //              = 5 Max Likelihood Estimate as test statistic
  //              = 6 Number of observed event as test statistic
  //

  // 0,3,true for frequentist CLs; 2,3,true for asymptotic CLs; 0,2,false for FC
  int calculatorType = 2;
  int testStatType = 2;
  bool useCLs = false;
  // root> StandardHypoTestInvDemo("filename.c_str()",
  // "workspace name",
  // "S+B modelconfig name",
  // "B model name",
  // "data set name",
  // calculator type, 
  // test statistic type, 
  // use CLS,
  // number of points, 
  // xmin, 
  // xmax, 
  // number of toys, 
  // use number counting)
  TStopwatch tw; 
  tw.Start();

  pair<double,double> lims = StandardHypoTestInvDemo(f->GetName(),
      wsname,
      sbHypo,
      bHypo,
      "data",                 
      calculatorType,
      testStatType, 
      useCLs,  
      20,   
      poimin,  
      poimax, 
      1000,
      false,
      0);
  // root> StandardHypoTestInvDemo("filename.c_str()",
  // "workspace name",
  // "S+B modelconfig name",
  // "B model name",
  // "data set name",
  // calculator type, 
  // test statistic type, 
  // use CLS,
  // number of points, 
  // xmin, 
  // xmax, 
  // number of toys, 
  // use number counting)

  std::streambuf *coutbuf = std::cout.rdbuf();
  std::cout.rdbuf(of.rdbuf());
  tw.Print();
  std::cout.rdbuf(coutbuf);

  of << "Feldman-Cousins interval from " 
    << "StandardHypoTestInvDemo(" << f->GetName() << ","
    << wsname << ","
    <<sbHypo<<","
    <<bHypo<<","
    <<"data"<<","
    <<calculatorType<<","
    <<testStatType<<","
    <<useCLs<<","  
    <<20<<","   
    <<poimin<<","  
    <<poimax<<"," 
    <<1000<<","
    <<false<<","
    <<0<<");" << endl;
  of << lims.first << " " << lims.second << endl;
}
