/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooMyPdfPP.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooMyPdfPP) 

 RooMyPdfPP::RooMyPdfPP(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _a1,
                        RooAbsReal& _a2,
                        RooAbsReal& _a3,
                        RooAbsReal& _a4,
                        RooAbsReal& _a5) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   a1("a1","a1",this,_a1),
   a2("a2","a2",this,_a2),
   a3("a3","a3",this,_a3),
   a4("a4","a4",this,_a4),
   a5("a5","a5",this,_a5)
 { 
 } 


 RooMyPdfPP::RooMyPdfPP(const RooMyPdfPP& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   a1("a1",this,other.a1),
   a2("a2",this,other.a2),
   a3("a3",this,other.a3),
   a4("a4",this,other.a4),
   a5("a5",this,other.a5)
 { 
 } 



 Double_t RooMyPdfPP::evaluate() const 
 { 
	// ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
	
	//Fix all parameters except norms
	/*Double_t ratio1 = 0.246361;
	Double_t muErf1 = 8.68177;
	Double_t sigma1 = 0.260365;
	Double_t muExp1 = 8;
	Double_t lambdaExp1 = 1.57003;
	Double_t lambdaDecay1 = 3.42257;
	Double_t ratio2 = 0.469979;
	Double_t muErf2 = 9.33062;
	Double_t sigma2 = 0.586417;
	Double_t muExp2 = 7.95747;
	Double_t lambdaExp2 = 2.47556;
	Double_t lambdaDecay2 = 3.44403;
	Double_t ratio3 = 1.16533;
	Double_t muErf3 = 9.93725;
	Double_t sigma3 = 0.877941;
	Double_t muExp3 = 7.68777;
	Double_t lambdaExp3 = 1.77457;
	Double_t lambdaDecay3 = 3.69275;
	Double_t ratio4 = 3.3301;
	Double_t muErf4 = 10;
	Double_t sigma4 = 1.17265;
	Double_t muExp4 = 7.40884;
	Double_t lambdaExp4 = 0.598727;
	Double_t lambdaDecay4 = 4.0446;
	Double_t ratio5 = 2.09825;
	Double_t muErf5 = 10;
	Double_t sigma5 = 1.48736;
	Double_t muExp5 = 6.91645;
	Double_t lambdaExp5 = 0.909955;
	Double_t lambdaDecay5 = 4.39846;*/
	
	//Parameters with 4 bins, as of 11_8_17
	Double_t ratio1 = 11.0379;
	Double_t muErf1 = 8.85392;
	Double_t sigma1 = 0.395047;
	Double_t muExp1 = 7.89129;
	Double_t lambdaExp1 = 0.778889;
	Double_t lambdaDecay1 = 5.01515;
	Double_t ratio2 = 7.04574;
	Double_t muErf2 = 9.59208;
	Double_t sigma2 = 0.871372;
	Double_t muExp2 = 7.96302;
	Double_t lambdaExp2 = 0.178231;
	Double_t lambdaDecay2 = 5.10247;
	Double_t ratio3 = 1.62887;
	Double_t muErf3 = 10.367;
	Double_t sigma3 = 1.14999;
	Double_t muExp3 = 7.17098;
	Double_t lambdaExp3 = 1.15836;
	Double_t lambdaDecay3 = 5.32505;
	Double_t ratio4 = 2.81053;
	Double_t muErf4 = 10;
	Double_t sigma4 = 2.10109;
	Double_t muExp4 = 6.51865;
	Double_t lambdaExp4 = 0.797357;
	Double_t lambdaDecay4 = 6.46157;
	//these should not matter if only 4 bins are used.
	Double_t ratio5 = 2.09825;
	Double_t muErf5 = 10;
	Double_t sigma5 = 1.48736;
	Double_t muExp5 = 6.91645;
	Double_t lambdaExp5 = 0.909955;
	Double_t lambdaDecay5 = 4.39846;
	
	//Calculate
	Double_t erfpart, exppart, decay;
	
	erfpart = (TMath::Erf((x-muErf1)/(TMath::Sqrt(2)*sigma1))+1);
	exppart = 0;
	if (x > muExp1)
		exppart = 1-TMath::Exp(-(x-muExp1)/lambdaExp1);
	decay = TMath::Exp(-x/lambdaDecay1);
	Double_t part1 = a1*(ratio1*erfpart + exppart)*decay;
	
	erfpart = (TMath::Erf((x-muErf2)/(TMath::Sqrt(2)*sigma2))+1);
	exppart = 0;
	if (x > muExp2)
		exppart = 1-TMath::Exp(-(x-muExp2)/lambdaExp2);
	decay = TMath::Exp(-x/lambdaDecay2);
	Double_t part2 = a2*(ratio2*erfpart + exppart)*decay;
	
	erfpart = (TMath::Erf((x-muErf3)/(TMath::Sqrt(2)*sigma3))+1);
	exppart = 0;
	if (x > muExp3)
		exppart = 1-TMath::Exp(-(x-muExp3)/lambdaExp3);
	decay = TMath::Exp(-x/lambdaDecay3);
	Double_t part3 = a3*(ratio3*erfpart + exppart)*decay;
	
	erfpart = (TMath::Erf((x-muErf4)/(TMath::Sqrt(2)*sigma4))+1);
	exppart = 0;
	if (x > muExp4)
		exppart = 1-TMath::Exp(-(x-muExp4)/lambdaExp4);
	decay = TMath::Exp(-x/lambdaDecay4);
	Double_t part4 = a4*(ratio4*erfpart + exppart)*decay;
	
	erfpart = (TMath::Erf((x-muErf5)/(TMath::Sqrt(2)*sigma5))+1);
	exppart = 0;
	if (x > muExp5)
		exppart = 1-TMath::Exp(-(x-muExp5)/lambdaExp5);
	decay = TMath::Exp(-x/lambdaDecay5);
	Double_t part5 = a5*(ratio5*erfpart + exppart)*decay;
		
	return part1 + part2 + part3 + part4 + part5;
 } 



