/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYPDFPP
#define ROOMYPDFPP

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMyPdfPP : public RooAbsPdf {
public:
  RooMyPdfPP() {} ; 
  RooMyPdfPP(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _a1,
	      RooAbsReal& _a2,
	      RooAbsReal& _a3,
	      RooAbsReal& _a4,
	      RooAbsReal& _a5);
  RooMyPdfPP(const RooMyPdfPP& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyPdfPP(*this,newname); }
  inline virtual ~RooMyPdfPP() { }

protected:

  RooRealProxy x ;
  RooRealProxy a1 ;
  RooRealProxy a2 ;
  RooRealProxy a3 ;
  RooRealProxy a4 ;
  RooRealProxy a5 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMyPdfPP,1) // Your description goes here...
};
 
#endif
