// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/deathold/work/CMS/analysis/Upsilon_RAA/upsilonRAA5TeV/Systematic/CBGaus_Variation/./doFitUpsilon_Data_CBGaus.C";

#endif
